#                        _                             _       __      _       __     ___            _        
#  _ __ ___  _   _ _ __ (_)_ __        _ __   ___   __| | ___ / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ ` _ \| | | | '_ \| | '_ \ _____| '_ \ / _ \ / _` |/ _ \ || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | | | | | | |_| | | | | | | | |_____| | | | (_) | (_| |  __/ || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_| |_| |_|\__,_|_| |_|_|_| |_|     |_| |_|\___/ \__,_|\___| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                                                             \_\_|        |___/_/                            
# boot-script
- name: boot-script | Enable munin-node
  when: munin.node.enabled == True
  service:
    name:    "munin-node"
    enabled: "yes"

- name: boot-script | Disable munin-node
  when: munin.node.enabled == False
  service:
    name:    "munin-node"
    enabled: "no"

- name: boot-script | Start munin-node
  when: munin.node.started == True
  service:
    name:  "munin-node"
    state: "started"

- name: boot-script | Stop munin-node
  when: munin.node.started == False
  service:
    name:  "munin-node"
    state: "stopped"

