#                        _                             _       __      _       __     ___            _        
#  _ __ ___  _   _ _ __ (_)_ __        _ __   ___   __| | ___ / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ ` _ \| | | | '_ \| | '_ \ _____| '_ \ / _ \ / _` |/ _ \ || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | | | | | | |_| | | | | | | | |_____| | | | (_) | (_| |  __/ || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_| |_| |_|\__,_|_| |_|_|_| |_|     |_| |_|\___/ \__,_|\___| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                                                             \_\_|        |___/_/                            
# install-pkg
- block:
    - name: install-pkg | EPEL repository should be installed
      yum:
        name:  "epel-release"
        state: "present"

    - name: install-pkg | munin-node should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
        enablerepo: "epel"
      with_items:
        - "munin-node"
  when: ansible_os_family == "RedHat"

- name: install-pkg | Related Perl modules should be installed
  cpanm:
    name: "{{ item }}"
  with_items:
    - "LWP::UserAgent"
    - "IPC::Cmd"
    - "JSON::Syck"
    - "Net::CIDR"

