#                        _                             _       __      _       __     ___            _        
#  _ __ ___  _   _ _ __ (_)_ __        _ __   ___   __| | ___ / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ ` _ \| | | | '_ \| | '_ \ _____| '_ \ / _ \ / _` |/ _ \ || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | | | | | | |_| | | | | | | | |_____| | | | (_) | (_| |  __/ || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_| |_| |_|\__,_|_| |_|_|_| |_|     |_| |_|\___/ \__,_|\___| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                                                             \_\_|        |___/_/                            
# install-pkg
- block:
    - name: install-pkg | EPEL repository should be installed
      yum:
        name:  "epel-release"
        state: "present"

    - name: install-pkg | munin-node should be installed
      yum:
        name:  "munin-node"
        state: "present"
        enablerepo: "epel"
  when: ansible_os_family == "RedHat"

- name: install-pkg | cpanm shoudl be downloaded
  get_url:
    url:  "http://cpanmin.us/"
    dest: "{{ munin.node.workingdir }}/cpanm"

- name: install-pkg | /usr/local/bin/cpanm
  shell: >
    install -o root -m 0755 cpanm /usr/local/bin
  args:
    chdir:   "{{ munin.node.workingdir }}"
    creates: "/usr/local/bin/cpanm"

- name: install-pkg | Related Perl modules should be installed
  cpanm:
    name:       "{{ item }}"
    executable: "/usr/local/bin/cpanm"
  with_items:
    - "LWP::UserAgent"
    - "IPC::Cmd"
    - "JSON::Syck"
    - "Net::CIDR"

